import NoSsr from "@/utils/NoSsr";
import type { Metadata } from "next";
import "../.././src/index.scss";
import MainProvider from "./MainProvider";
import { I18nProvider } from "./i18n/i18n-context";
import { detectLanguage } from "./i18n/server";
import SessionWrapper from "@/CommonComponent/SessionWrapper";
import { getServerSession } from "next-auth";
import { authoption } from "./api/auth/[...nextauth]/authOption";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Edmin - Premium Admin Template",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const lng = await detectLanguage();
  const session = await getServerSession(authoption);

  return (
    <I18nProvider language={lng}>
      <html lang={lng}>
        <head>
          <link rel='icon' href='/assets/images/favicon/favicon.png' type='image/x-icon' />
          <link rel='shortcut icon' href='/assets/images/favicon/favicon.png' type='image/x-icon' />
          <link rel='preconnect' href='https://fonts.googleapis.com' />
          <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='' />
          <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap' rel='stylesheet' />
          <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyAjeJEPREBQFvAIqDSZliF0WjQrCld-Mh0'></script>
        </head>
        <body>
          <NoSsr>
            <SessionWrapper session={session}>
              <MainProvider>{children}</MainProvider>
            </SessionWrapper>
            <ToastContainer />
          </NoSsr>
        </body>
      </html>
    </I18nProvider>
  );
}
